# Generated by Django 5.1 on 2024-09-04 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="columnId",
        ),
        migrations.AddField(
            model_name="todo",
            name="column",
            field=models.CharField(default="todo", max_length=20),
        ),
        migrations.AddField(
            model_name="todo",
            name="projectId",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todos",
                to="api.project",
            ),
        ),
    ]
