# Generated by Django 5.1 on 2024-09-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_todo_columnid_todo_column_todo_projectid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="column",
            name="slug",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="column",
            name="title",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
